package ui;

import com.mycompany.core.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class EditAppointmentView extends javax.swing.JFrame {
    Appointment app;
    private static final String APPFILENAME = "appointment.txt";
    private static final String FILEHEADER = "ID||Date||PatientID||DoctorName||DepartmentName" + System.lineSeparator();
    /**
     * Creates new form EditSalesExecView
     */
    public EditAppointmentView() {
        initComponents();
    }
    
    public EditAppointmentView(Appointment app){
        this.app = app;
        initComponents();
        loadTextField();
    }
    
    private void loadTextField(){
        txtID.setText(app.getID());
        txtDate.setText(app.getDate());
        txtPatientID.setText(app.getPatientID());
        txtDoctorName.setText(app.getDoctorName());
        txtDeptName.setText(app.getDepartmentName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        txtDeptName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Details");
        setLocation(new java.awt.Point(500, 150));
        setResizable(false);

        jPanel2.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        jLabel4.setText("Edit Appointment Details");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(160, 20, 550, 49);

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel3.setText("Patient ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(200, 240, 110, 30);

        txtPatientID.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jPanel2.add(txtPatientID);
        txtPatientID.setBounds(400, 240, 218, 24);

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel2.setText("Date");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 180, 80, 20);

        txtDate.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel2.add(txtDate);
        txtDate.setBounds(400, 180, 218, 24);

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel5.setText("Doctor's Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(200, 300, 140, 30);

        btnConfirm.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm Changes");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirm);
        btnConfirm.setBounds(420, 440, 190, 25);

        btnCancel.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);
        btnCancel.setBounds(220, 440, 100, 25);

        jLabel9.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel9.setText("ID");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(200, 120, 90, 20);

        txtID.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtID);
        txtID.setBounds(400, 120, 218, 24);

        txtDoctorName.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jPanel2.add(txtDoctorName);
        txtDoctorName.setBounds(400, 300, 218, 24);

        txtDeptName.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jPanel2.add(txtDeptName);
        txtDeptName.setBounds(400, 360, 218, 24);

        jLabel11.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel11.setText("Department Name");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(200, 360, 150, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        app.setID(txtID.getText());
        app.setDate(txtDate.getText());
        app.setPatientID(txtPatientID.getText());
        app.setDoctorName(txtDoctorName.getText());
        app.setDepartmentName(txtDeptName.getText());
        try (BufferedReader br = new BufferedReader(new FileReader(APPFILENAME))) {
            String row;
            String fileData = "";
            br.readLine();
            while ((row = br.readLine()) != null) {
                String[] data = row.split("\\|\\|");
                String txtId = data[0];
                if (app.getID().equals(txtId)) {
                    fileData += app.getID() + "||" + app.getDate() + "||" + app.getPatientID() + "||"
                    + app.getDoctorName() + "||" + app.getDepartmentName() + System.lineSeparator();
                } else {
                    fileData += row + System.lineSeparator();
                }
            }
            try(BufferedWriter bw = new BufferedWriter(new FileWriter(APPFILENAME))){
                bw.write(FILEHEADER);
                bw.write(fileData);
            }
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        //new UserProfileManager().editUser(customer);
        this.dispose();
        new ManageAppointmentView().setVisible(true);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        new ManageAppointmentView().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAppointmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeptName;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPatientID;
    // End of variables declaration//GEN-END:variables
}
